title: HAUDA
description: HAUDA Producciones es una empresa localizada en Lekumberri, Navarra. Está enfocada a la producción audiovisual, la comunicación, el diseño gráfico, el diseño web y la fotografía.

sass:
    sass_dir: _sass
    
gems:
    - jekyll
    